services:

  rmoscetti_cheshire-cat-core:
    image: rmoscetti_cheshire_cat:1.7.1
    container_name: rmoscetti_cat
    depends_on:
      - qdrant
      - ollama
      - mariadb
    env_file:
      - .cat
    ports:
      - 1865:80
      - 5678:5678
    volumes:
      - /home/r.moscetti/cheshire-cat-ai/static:/app/cat/static
      - /home/r.moscetti/cheshire-cat-ai/plugins:/app/cat/plugins
      - /home/r.moscetti/cheshire-cat-ai/data:/app/cat/data
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    container_name: rmoscetti_qdrant
    env_file:
      - .qdrant
    ports:
      - 6333:6333
    expose:
      - 6333
    volumes:
      - /home/r.moscetti/cheshire-cat-ai/qdrant_memory:/qdrant/storage
    restart: unless-stopped
    
  ollama:
    image: ollama/ollama:latest
    container_name: rmoscetti_ollama
    ports:
      - 11444:11434
    expose:
      - 11434
    environment:
      - gpus=all
    volumes:
      - /home/r.moscetti/ollama:/root/.ollama
    restart: unless-stopped

  mariadb:
    image: mariadb:latest
    container_name: rmoscetti_mariadb
    ports:
      - 3306:3306
    expose:
      - 3306
    env_file:
      - .mariadb
    volumes:
      - /home/r.moscetti/cheshire-cat-ai/mysql:/var/lib/mysql
    restart: unless-stopped